"""N0.3: generate the synthetic wearable series.

SYNTHETIC. No device, no real person. A deterministic seed keeps the demo
reproducible; an injectable burnout trend bends the final days so the pattern
engine has something true to find:

    sleep down, resting heart rate up a few bpm, HRV down twenty to thirty percent.

Dates always end today, so "last night" is accurate whenever it is run.

    python scripts/gen_wearables.py                # default 14 days, burnout on
    python scripts/gen_wearables.py --days 21 --no-burnout --seed 7
"""
import argparse
import json
import math
import random
from datetime import date, timedelta
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
OUT = ROOT / "data" / "wearable_sim.json"

BASE_SLEEP = 7.4        # hours on an unstressed night
BASE_RHR = 58           # resting heart rate, bpm
BASE_HRV = 68           # rmssd, ms
BASE_STEPS = 8200


def build(days: int, burnout: bool, seed: int) -> dict:
    rng = random.Random(seed)
    today = date.today()
    rows = []

    # the trend ramps over the final stretch so the last few days carry it
    ramp_start = days - 5

    for i in range(days):
        d = today - timedelta(days=days - 1 - i)
        # gentle weekly rhythm: weekends sleep a little longer
        weekend = 0.5 if d.weekday() >= 5 else 0.0
        circadian = 0.25 * math.sin(i / 2.4)

        severity = 0.0
        if burnout and i >= ramp_start:
            severity = (i - ramp_start + 1) / 5.0   # 0.2 .. 1.0

        sleep = BASE_SLEEP + weekend + circadian - 2.9 * severity + rng.uniform(-0.28, 0.28)
        sleep = round(max(3.9, min(9.0, sleep)), 1)

        deep_ratio = 0.22 - 0.06 * severity + rng.uniform(-0.02, 0.02)
        deep = int(max(25, sleep * 60 * deep_ratio))

        rhr = BASE_RHR + 6.5 * severity + rng.uniform(-1.4, 1.4)
        rhr = int(max(48, min(88, round(rhr))))

        hrv = BASE_HRV * (1 - 0.30 * severity) + rng.uniform(-3.5, 3.5)
        hrv = int(max(20, min(100, round(hrv))))

        steps = int(BASE_STEPS * (1 - 0.28 * severity) + rng.uniform(-900, 900))
        steps = max(1200, steps)

        stress = int(max(8, min(95, round(30 + 48 * severity + rng.uniform(-6, 6)))))

        rows.append({
            "date": d.isoformat(),
            "sleep_hours": sleep,
            "deep_sleep_min": deep,
            "resting_hr": rhr,
            "hrv_rmssd": hrv,
            "steps": steps,
            "stress_score": stress,
        })

    late = [
        f"{(today - timedelta(days=k)).isoformat()}T0{1 + j % 2}:{28 + j:02d}"
        for j, k in enumerate((4, 2, 0))
    ]

    return {
        "_comment": "SYNTHETIC, generated by scripts/gen_wearables.py. "
                    "No real device data, no real person. Regenerate any time.",
        "source": "SIMULATED wearable data (no real device). "
                  "HealthKit / Google Fit integration is roadmap.",
        "generated_for_days": days,
        "burnout_trend": burnout,
        "seed": seed,
        "days": rows,
        "late_sessions": late,
        # kept so older readers of this file keep working
        "sleep_hours": [{"date": r["date"], "hours": r["sleep_hours"]} for r in rows],
    }


def main() -> None:
    ap = argparse.ArgumentParser(description="generate synthetic wearable data")
    ap.add_argument("--days", type=int, default=14)
    ap.add_argument("--seed", type=int, default=42)
    ap.add_argument("--no-burnout", action="store_true")
    a = ap.parse_args()

    data = build(a.days, not a.no_burnout, a.seed)
    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text(json.dumps(data, indent=2) + "\n", encoding="utf-8")

    rows = data["days"]
    first, last = rows[0], rows[-1]
    print(f"wrote {OUT.relative_to(ROOT)}  ({len(rows)} days, burnout={data['burnout_trend']})")
    print(f"  {first['date']}  sleep {first['sleep_hours']}h  rhr {first['resting_hr']}  hrv {first['hrv_rmssd']}")
    print(f"  {last['date']}  sleep {last['sleep_hours']}h  rhr {last['resting_hr']}  hrv {last['hrv_rmssd']}")

    base = rows[:7]
    recent = rows[-3:]
    hrv_b = sum(r["hrv_rmssd"] for r in base) / len(base)
    hrv_r = sum(r["hrv_rmssd"] for r in recent) / len(recent)
    rhr_b = sum(r["resting_hr"] for r in base) / len(base)
    rhr_r = sum(r["resting_hr"] for r in recent) / len(recent)
    print(f"  HRV  7-day baseline {hrv_b:.0f} ms -> 3-day {hrv_r:.0f} ms "
          f"({(hrv_r - hrv_b) / hrv_b * 100:+.0f}%)")
    print(f"  RHR  7-day baseline {rhr_b:.0f} bpm -> 3-day {rhr_r:.0f} bpm "
          f"({rhr_r - rhr_b:+.0f} bpm)")


if __name__ == "__main__":
    main()
